### ISSUE TITLE
Preloaded association with nil values causes: NoMethodError, "undefined method 'jit_preloader' for nil:NilClass"

### ISSUE THREAD

**Issue by djlmills** [clio/jit_preloader#55]
You have to work hard to do it, but it is possible for `preloaded_records` to contain `nil` values. This then causes an error **NoMethodError, "undefined method 'jit_preloader' for nil:NilClass"** when attempting to access a nested relation. This error prevents us from globally enabling jit_preloader.

Issue is present in Rails 5 (`ar5_association.rb`). Appears to be resolved in Rails 6 (`ar6_association.rb`). Not verified for Rails 7.
```Ruby
module JitPreloader
  module PreloaderAssociation
    def run
      return unless (reflection.scope.nil? || reflection.scope.arity == 0) && klass.ancestors.include?(ActiveRecord::Base)

      super.tap do
        if preloaded_records.any? && preloaded_records.none?(&:jit_preloader) # <-- Fails if preloaded_records contains nil values
          JitPreloader::Preloader.attach(preloaded_records) if owners.any?(&:jit_preloader) || JitPreloader.globally_enabled?
        end
      end
    end
```

I've patched it locally by changing:
```Ruby
if preloaded_records.any? && preloaded_records.none?(&:jit_preloader)
```
to
```Ruby
if preloaded_records.any? && preloaded_records.compact.none?(&:jit_preloader)
```

Relevant part of the stack trace:
```
"/jit_preloader-1.0.2/lib/jit_preloader/active_record/associations/preloader/ar5_association.rb:25:in `block in run'",
"/jit_preloader-1.0.2/lib/jit_preloader/active_record/associations/preloader/ar5_association.rb:23:in `tap'",
"/jit_preloader-1.0.2/lib/jit_preloader/active_record/associations/preloader/ar5_association.rb:23:in `run'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:142:in `block (2 levels) in preloaders_for_one'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:140:in `each'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:140:in `map'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:140:in `block in preloaders_for_one'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:139:in `each'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:139:in `flat_map'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:139:in `preloaders_for_one'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:106:in `preloaders_on'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:93:in `block in preload'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:92:in `each'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:92:in `flat_map'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:92:in `preload'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader/through_association.rb:11:in `run'",
"/jit_preloader-1.0.2/lib/jit_preloader/active_record/associations/preloader/ar5_association.rb:23:in `run'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:142:in `block (2 levels) in preloaders_for_one'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:140:in `each'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:140:in `map'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:140:in `block in preloaders_for_one'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:139:in `each'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:139:in `flat_map'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:139:in `preloaders_for_one'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:106:in `preloaders_on'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:93:in `block in preload'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:92:in `each'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:92:in `flat_map'",
"/activerecord-5.2.8.1/lib/active_record/associations/preloader.rb:92:in `preload'",
"/jit_preloader-1.0.2/lib/jit_preloader/preloader.rb:19:in `jit_preload'",
"/jit_preloader-1.0.2/lib/jit_preloader/active_record/associations/collection_association.rb:8:in `load_target'",
"/activerecord-5.2.8.1/lib/active_record/associations/collection_proxy.rb:46:in `load_target'",
"/activerecord-5.2.8.1/lib/active_record/associations/collection_proxy.rb:1004:in `records'",
"/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:71:in `each'",
```

**Comment by djlmills** [comment]
Contrived example (books can have more than one author), but this is roughly the sequence of events that causes the issue:
```Ruby
class Author < ApplicationRecord
  has_many :books, inverse_of: :author
  has_many :publishers, through: :books
end

class Book < ApplicationRecord
  belongs_to :author
  belongs_to :publisher
end

class Publishers < ApplicationRecord
  has_many :books, inverse_of: :publisher
  has_many :authors, through: :books
end

an_author = Author.create!(name: "Joe")
a_publisher = Publisher.create!(company_name: "Bestsellers Inc.")

published_book = Book.create!(author: an_author, publisher: a_publisher, title: "My masterwork")
unpublished_book = Book.create!(author: an_author, publisher: nil, title: "A work in progress")

# assuming jit_preload is globally enabled

authors = Author.all

# This is the root cause of the issue
# The two stage mapping causes a nil value in the preloaded publishers
_publishers_indirect = authors.map(&:books).map(&:publisher)

# to_a calls load, which triggers the issue
_publishers_direct = authors.map(&:publishers).to_a
```

**Comment by djlmills** [comment]
Unable to replicate for Rails 6.x.
